// src/App.jsx
import { useState } from 'react'
import NavigationRail from './components/NavigationRail.jsx'
import KLineOutboundTime from './components/KLineOutboundTime.jsx'
import KLineInboundTime from './components/KLineInboundTime.jsx'
import KLineOutboundSpeed from './components/KLineOutboundSpeed.jsx'
import KLineInboundSpeed from './components/KLineInboundSpeed.jsx'

const views = {
    outboundTime: KLineOutboundTime,
    inboundTime: KLineInboundTime,
    outboundSpeed: KLineOutboundSpeed,
    inboundSpeed: KLineInboundSpeed,
}

function App() {
    const [activeView, setActiveView] = useState('inboundTime')
    const ActiveComponent = views[activeView] ?? KLineInboundTime

    return (
        <div className="app-layout">
            <NavigationRail activeView={activeView} onSelectView={setActiveView} />
            <main className="content">
                <ActiveComponent />
            </main>
        </div>
    )
}

export default App

// src/App.vue
<script setup>
import { computed, ref } from 'vue'
import NavigationRail from './components/NavigationRail.vue'
import KLineOutboundTime from './components/KLineOutboundTime.vue'
import KLineInboundTime from './components/KLineInboundTime.vue'
import KLineOutboundSpeed from './components/KLineOutboundSpeed.vue'
import KLineInboundSpeed from './components/KLineInboundSpeed.vue'

const views = {
    outboundTime: KLineOutboundTime,
    inboundTime: KLineInboundTime,
    outboundSpeed: KLineOutboundSpeed,
    inboundSpeed: KLineInboundSpeed,
}

const activeView = ref('inboundTime')

const currentComponent = computed(() => views[activeView.value] ?? KLineInboundTime)

const handleSelect = (view) => {
    if (view in views) {
        activeView.value = view
    }
}
</script>

<template>
    <div class="app-layout">
        <NavigationRail :active-view="activeView" @select-view="handleSelect" />
        <main class="content">
            <component :is="currentComponent" />
        </main>
    </div>
</template>

<style scoped>
.app-layout {
    display: flex;
    height: 100vh;
    align-items: stretch;
}

.content {
    flex: 1;
    padding: 16px 0;
    overflow: auto;
}
</style>
